name: Sync Image to Aliyun  Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: crpi-7friixgo15237y1p.cn-shanghai.personal.cr.aliyuncs.com
        username: ${{secrets.Sdyizhaosheng163}}
        password: ${{secrets.sd.89731116}}
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://docker.io/mysql:5.5.42 docker://crpi-7friixgo15237y1p.cn-shanghai.personal.cr.aliyuncs.com/yizhaosheng/docker-images:mysql:5.5.42
